name: Rust CI

on:
  push:
    branches: [ "main" ] # Adjust to your main branch name
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    name: Build, Lint, and Test
    runs-on: ubuntu-latest # Can also test on windows-latest, macos-latest
    strategy:
      matrix:
        rust: [stable, beta] # Test on multiple Rust versions
    steps:
      - uses: actions/checkout@v3
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}
          components: rustfmt, clippy

      - name: Install cargo-audit (for vulnerability check testing)
        if: matrix.rust == 'stable' # Only need it once
        run: cargo install cargo-audit

      - name: Install cargo-udeps (if using for unused dep check)
        if: matrix.rust == 'stable' # Only need it once
        run: cargo install cargo-udeps --locked

      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2
        # Caches target directory and Cargo registry/git dependencies

      - name: Check formatting
        run: cargo fmt --all -- --check

      - name: Lint with Clippy
        run: cargo clippy --all-targets -- -D warnings # Fail on warnings

      - name: Build
        run: cargo build --verbose

      - name: Run tests
        run: cargo test --verbose